---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# program-objectives

A place for discussion of UTSC statistics program objectives, with curriculum map for program review in mind.

## Files:

- `program-objectives.txt`: a sketch of some things students ought to be able to do by the end of their programs. Indented points are subpoints of main points (starting at the beginning of the line). The points labelled Part A and Part B are dummy subpoints to show that you can go three levels deep.
- `applied-minor-courses.txt`: a list of (our) courses in the Applied Minor program.

## I need help!

- make files like `applied-minor-courses.txt` that contain all the courses you want to include for your program
- take a look at my program objectives, in `program-objectives.txt` and suggest changes. Make a pull request (if you know how), or mention it in an Issue (or email me).
- if you want to be added as a Collaborator, let me know your Github userid.
- the whole thing is an R Studio project, so you can grab your own copy by File - New Project - From Github.

## My aims (with R)

- to make a numbered list of program objectives, 1(a), 1(b), 1(c) etc. This is done [here](https://raw.githubusercontent.com/nxskok/program-objectives/master/objectives_formatted.txt), and will be changed as we add/remove objectives. (The script is [here](https://raw.githubusercontent.com/nxskok/program-objectives/master/process-objectives.Rmd)).
- to make a blank curriculum map spreadsheet for each program (once I have the courses for that program)

spreadsheets can then be filled in eg. with colour to illustrate how the courses contribute to the program objectives.

